# Generated by Django 4.2.7 on 2023-12-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absentee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenteeapplication',
            name='reason_type',
            field=models.CharField(blank=True, choices=[('mitigating', 'Mitigating Circumstance'), ('sickleave', 'Sick Leave'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
