# Generated by Django 4.2.7 on 2023-12-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('absentee', '0002_absenteeapplication_reason_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenteeapplication',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
    ]
