import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import App from '@/components/query-provider'
import { Toaster } from '@/components/ui/toaster'
import Nav from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <App>
        <body className={inter.className}>
          <Nav />
          <div className="container mt-20">
            {children}
          </div>
          <Toaster />
        </body>
      </App>
    </html>
  )
}
